export const ALL_EXERCISES = [
  { name: 'Ab Wheel Rollouts', muscle: 'Core' },
  { name: 'Arnold Press (Dumbbell)', muscle: 'Shoulders' },
  { name: 'Back Extension', muscle: 'Back' },
  { name: 'Ball Slams', muscle: 'Full Body' },
  { name: 'Barbell Row', muscle: 'Back' },
  { name: 'Flat Barbell Bench Press', muscle: 'Chest' },
  { name: 'Bench Press (Dumbbell)', muscle: 'Chest' },
  { name: 'Bicep Curl (Barbell)', muscle: 'Arms' },
  { name: 'Bicep Curl Dumbbell Supinated', muscle: 'Arms' },
  { name: 'Barbell Bulgarian Split Squat', muscle: 'Legs' },
  { name: 'Dumbbell Bulgarian Split Squat', muscle: 'Legs' },
  { name: 'Cable Crunch', muscle: 'Core' },
  { name: 'Bicep Cable Curl', muscle: 'Arms' },
  { name: 'Cable Chest Fly', muscle: 'Chest' },
  { name: 'Side Cable Lateral Raise', muscle: 'Shoulders' },
  { name: 'Cable Row', muscle: 'Back' },

  { name: 'Chest Dip', muscle: 'Chest' },
  { name: 'Chin Up', muscle: 'Back' },
  { name: 'Clean and Press', muscle: 'Full Body' },
  { name: 'Close Grip Smith Chest Press', muscle: 'Chest' },
  { name: 'Crunch', muscle: 'Core' },
  { name: 'Dead Bug', muscle: 'Core' },
  { name: 'Deadlift (Barbell)', muscle: 'Back' },
  { name: 'Decline Bench Press', muscle: 'Chest' },
  { name: 'Decline Crunch', muscle: 'Core' },
  { name: 'Flat Dumbbell Chest Press', muscle: 'Chest' },
  { name: 'Dumbbell Chest Pullover', muscle: 'Chest' },
  { name: 'Dumbbell Fly', muscle: 'Chest' },
  { name: 'Face Pull', muscle: 'Shoulders' },
  { name: "Farmer's Walk", muscle: 'Full Body' },
  { name: 'Front Raise', muscle: 'Shoulders' },
  { name: 'Front Squat', muscle: 'Legs' },
  { name: 'Glute Bridge', muscle: 'Legs' },
  { name: 'Goblet Squat', muscle: 'Legs' },
  { name: 'Good Morning', muscle: 'Back' },
  { name: 'Hack Squat', muscle: 'Legs' },
  { name: 'Hammer Curl', muscle: 'Arms' },
  { name: 'Hang Clean', muscle: 'Full Body' },
  { name: 'Hanging Leg Raise', muscle: 'Core' },
  { name: 'Hip Thrust (Barbell)', muscle: 'Legs' },
  { name: 'Hollow Body Hold', muscle: 'Core' },
  { name: 'Incline Barbell Press', muscle: 'Chest' },
  { name: 'Dumbbell Incline Chest Press', muscle: 'Chest' },
  { name: 'Incline Smith Chest Press', muscle: 'Chest' },
  { name: 'Incline Curl', muscle: 'Arms' },
  { name: 'Iso-Lateral Row (Machine)', muscle: 'Back' },
  { name: 'JM Press', muscle: 'Arms' },
  { name: 'Jump Squat', muscle: 'Legs' },
  { name: 'Kettlebell Swing', muscle: 'Full Body' },
  { name: 'L-Sit', muscle: 'Core' },
  { name: 'Lat Pulldown', muscle: 'Back' },
  { name: 'Lateral Raise (Dumbbell)', muscle: 'Shoulders' },
  { name: 'Lateral Raise (Machine)', muscle: 'Shoulders' },
  { name: 'Lying Hamstring Curl', muscle: 'Legs' },
  { name: 'Seated Hamstring Curl', muscle: 'Legs' },
  { name: 'Leg Extension (Machine)', muscle: 'Legs' },
  { name: 'Leg Press', muscle: 'Legs' },
  { name: 'Leg Press Calf Raise', muscle: 'Legs' },
  { name: 'Lunge (Barbell)', muscle: 'Legs' },
  { name: 'Lunge (Dumbbell)', muscle: 'Legs' },
  { name: 'Meadows Row', muscle: 'Back' },
  { name: 'Mountain Climber', muscle: 'Core' },
  { name: 'Nordic Curl', muscle: 'Legs' },
  { name: 'Overhead Press (Barbell)', muscle: 'Shoulders' },
  { name: 'Overhead Press (Dumbbell)', muscle: 'Shoulders' },
  { name: 'Overhead Tricep Extension (Dumbbell)', muscle: 'Arms' },
  { name: 'Pallof Press', muscle: 'Core' },
  { name: 'Pec Deck (Machine)', muscle: 'Chest' },
  { name: 'Pendlay Row', muscle: 'Back' },
  { name: 'Plank', muscle: 'Core' },
  { name: 'Preacher Curl', muscle: 'Arms' },
  { name: 'Pull Up', muscle: 'Back' },
  { name: 'Pullover (Machine)', muscle: 'Back' },
  { name: 'Push Up', muscle: 'Chest' },
  { name: 'Rear Delt Fly', muscle: 'Shoulders' },
  { name: 'Reverse Curl', muscle: 'Arms' },
  { name: 'Reverse Lunge', muscle: 'Legs' },
  { name: 'Romanian Deadlift (Barbell)', muscle: 'Legs' },
  { name: 'Romanian Deadlift (Dumbbell)', muscle: 'Legs' },
  { name: 'Rope Pushdown', muscle: 'Arms' },
  { name: 'Russian Twist', muscle: 'Core' },
  { name: 'Seated Cable Fly', muscle: 'Chest' },
  { name: 'Seal Row', muscle: 'Back' },
  { name: 'Seated Row (Machine)', muscle: 'Back' },
  { name: 'Shrug (Barbell)', muscle: 'Shoulders' },
  { name: 'Shrug (Dumbbell)', muscle: 'Shoulders' },
  { name: 'Side Lateral Raise', muscle: 'Shoulders' },
  { name: 'Single Arm Dumbbell Row', muscle: 'Back' },
  { name: 'Single Arm Overhead Cable Extension', muscle: 'Arms' },
  { name: 'Sissy Squat', muscle: 'Legs' },
  { name: 'Skull Crusher', muscle: 'Arms' },
  { name: 'Sled Push', muscle: 'Full Body' },
  { name: 'Smith Machine Squat', muscle: 'Legs' },
  { name: 'Spider Curl', muscle: 'Arms' },
  { name: 'Squat (Barbell)', muscle: 'Legs' },
  { name: 'Squat (Dumbbell)', muscle: 'Legs' },
  { name: 'Standing Calf Raise (Machine)', muscle: 'Legs' },
  { name: 'Standing Chest Press', muscle: 'Chest' },
  { name: 'Standing Press', muscle: 'Shoulders' },
  { name: 'Step Up', muscle: 'Legs' },
  { name: 'Straight Arm Pulldown', muscle: 'Back' },
  { name: 'Sumo Deadlift', muscle: 'Legs' },
  { name: 'T-Bar Row', muscle: 'Back' },
  { name: 'Thruster', muscle: 'Full Body' },
  { name: 'Trap Bar Deadlift', muscle: 'Legs' },
  { name: 'Tricep Dip', muscle: 'Arms' },
  { name: 'Tricep Pushdown (Cable)', muscle: 'Arms' },
  { name: 'Tricep Single Arm Extension', muscle: 'Arms' },
  { name: 'Turkish Get-Up', muscle: 'Full Body' },
  { name: 'Upright Row', muscle: 'Shoulders' },
  { name: 'V-Up', muscle: 'Core' },
  { name: 'Wide Grip Pull Up', muscle: 'Back' },
  { name: 'Wrist Curl', muscle: 'Arms' },
  { name: 'Zottman Curl', muscle: 'Arms' },
];

export const MUSCLES = ['All', 'Arms', 'Back', 'Chest', 'Core', 'Full Body', 'Legs', 'Shoulders'];

export const MUSCLE_COLORS = {
  'Arms': { bg: 'bg-rose-50 dark:bg-rose-950/30', text: 'text-rose-600 dark:text-rose-400' },
  'Back': { bg: 'bg-amber-50 dark:bg-amber-950/30', text: 'text-amber-600 dark:text-amber-400' },
  'Chest': { bg: 'bg-blue-100 dark:bg-blue-950/30', text: 'text-blue-500 dark:text-blue-400' },
  'Core': { bg: 'bg-emerald-50 dark:bg-emerald-950/30', text: 'text-emerald-600 dark:text-emerald-400' },
  'Full Body': { bg: 'bg-violet-50 dark:bg-violet-950/30', text: 'text-violet-600 dark:text-violet-400' },
  'Legs': { bg: 'bg-orange-50 dark:bg-orange-950/30', text: 'text-orange-600 dark:text-orange-400' },
  'Shoulders': { bg: 'bg-cyan-50 dark:bg-cyan-950/30', text: 'text-cyan-600 dark:text-cyan-400' },
};