export const EXAMPLE_SPLITS_DATA = {
  'upper-lower': {
    name: 'Upper-Lower',
    description: 'Alternate between upper and lower body days',
    label: 'Upper • Lower',
    schedule: [1, 1, 0, 1, 1, 0, 1], // 2 on, 1 off cycling — Upper, Lower, Rest, Upper, Lower, Rest, Upper (Sun starts next cycle)
    workouts: [
      {
        name: 'Upper Body Workout',
        emoji: '💪',
        exercises: [
          { name: 'Bench Press (Barbell)', muscle: 'Chest', sets: 2 },
          { name: 'Overhead Press (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Pull Up', muscle: 'Back', sets: 2 },
          { name: 'Barbell Row', muscle: 'Back', sets: 2 },
          { name: 'Lateral Raise (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Bicep Curl (Dumbbell)', muscle: 'Arms', sets: 2 },
          { name: 'Tricep Pushdown (Cable)', muscle: 'Arms', sets: 2 },
          { name: 'Face Pull', muscle: 'Shoulders', sets: 2 },
        ],
      },
      {
        name: 'Lower Body Workout',
        emoji: '🦵',
        exercises: [
          { name: 'Squat (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Deadlift (Barbell)', muscle: 'Back', sets: 2 },
          { name: 'Leg Press', muscle: 'Legs', sets: 2 },
          { name: 'Leg Curl (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Leg Extension (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Calf Raise (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Crunch', muscle: 'Core', sets: 2 },
          { name: 'Plank', muscle: 'Core', sets: 2 },
        ],
      },
    ],
  },
  'push-pull-legs': {
    name: 'Push-Pull-Legs',
    description: 'Push day, pull day, legs day — 3-day rotation',
    label: 'Push • Pull • Legs',
    schedule: [1, 1, 1, 0, 1, 1, 1], // Push, Pull, Legs, Rest, repeat
    workouts: [
      {
        name: 'Push Workout',
        emoji: '🏋️',
        subtitle: 'Chest + Triceps',
        exercises: [
          { name: 'Bench Press (Barbell)', muscle: 'Chest', sets: 2 },
          { name: 'Incline Bench Press (Dumbbell)', muscle: 'Chest', sets: 2 },
          { name: 'Dumbbell Fly', muscle: 'Chest', sets: 2 },
          { name: 'Overhead Press (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Lateral Raise (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Tricep Pushdown (Cable)', muscle: 'Arms', sets: 2 },
          { name: 'Skull Crusher', muscle: 'Arms', sets: 2 },
        ],
      },
      {
        name: 'Pull Workout',
        emoji: '🔙',
        subtitle: 'Back + Biceps',
        exercises: [
          { name: 'Deadlift (Barbell)', muscle: 'Back', sets: 2 },
          { name: 'Pull Up', muscle: 'Back', sets: 2 },
          { name: 'Barbell Row', muscle: 'Back', sets: 2 },
          { name: 'Seated Row (Machine)', muscle: 'Back', sets: 2 },
          { name: 'Face Pull', muscle: 'Shoulders', sets: 2 },
          { name: 'Bicep Curl (Dumbbell)', muscle: 'Arms', sets: 2 },
          { name: 'Hammer Curl', muscle: 'Arms', sets: 2 },
        ],
      },
      {
        name: 'Legs Workout',
        emoji: '🦵',
        subtitle: 'Legs + Abs',
        exercises: [
          { name: 'Squat (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Romanian Deadlift (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Leg Press', muscle: 'Legs', sets: 2 },
          { name: 'Leg Curl (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Leg Extension (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Calf Raise (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Crunch', muscle: 'Core', sets: 2 },
          { name: 'Plank', muscle: 'Core', sets: 2 },
        ],
      },
    ],
  },
  'full-body': {
    name: 'Full Body',
    description: 'Train every muscle group in one session',
    label: 'Full Body',
    schedule: [1, 0, 1, 0, 1, 0, 1], // M:FB, T:Rest, W:FB, T:Rest, F:FB, S:Rest, S:FB
    workouts: [
      {
        name: 'Full Body Workout',
        emoji: '🔥',
        subtitle: 'Chest • Back • Shoulders • Arms • Legs • Core',
        exercises: [
          { name: 'Squat (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Bench Press (Barbell)', muscle: 'Chest', sets: 2 },
          { name: 'Barbell Row', muscle: 'Back', sets: 2 },
          { name: 'Overhead Press (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Romanian Deadlift (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Pull Up', muscle: 'Back', sets: 2 },
          { name: 'Lateral Raise (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Bicep Curl (Dumbbell)', muscle: 'Arms', sets: 2 },
          { name: 'Tricep Pushdown (Cable)', muscle: 'Arms', sets: 2 },
          { name: 'Plank', muscle: 'Core', sets: 2 },
        ],
      },
    ],
  },
  'ul-ppl': {
    name: 'U L P P L',
    description: 'Upper-Lower then Push-Pull-Legs — 5-day rotation',
    label: 'Upper • Lower • Push • Pull • Legs',
    schedule: [1, 1, 1, 1, 1, 0, 1], // Upper, Lower, Push, Pull, Legs, Rest, repeat
    workouts: [
      {
        name: 'Upper Body Workout',
        emoji: '💪',
        subtitle: 'Chest • Back • Shoulders • Arms',
        exercises: [
          { name: 'Bench Press (Barbell)', muscle: 'Chest', sets: 2 },
          { name: 'Overhead Press (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Pull Up', muscle: 'Back', sets: 2 },
          { name: 'Barbell Row', muscle: 'Back', sets: 2 },
          { name: 'Lateral Raise (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Bicep Curl (Dumbbell)', muscle: 'Arms', sets: 2 },
          { name: 'Tricep Pushdown (Cable)', muscle: 'Arms', sets: 2 },
          { name: 'Face Pull', muscle: 'Shoulders', sets: 2 },
        ],
      },
      {
        name: 'Lower Body Workout',
        emoji: '🦵',
        subtitle: 'Quads • Hamstrings • Glutes • Core',
        exercises: [
          { name: 'Squat (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Deadlift (Barbell)', muscle: 'Back', sets: 2 },
          { name: 'Leg Press', muscle: 'Legs', sets: 2 },
          { name: 'Leg Curl (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Leg Extension (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Calf Raise (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Crunch', muscle: 'Core', sets: 2 },
          { name: 'Plank', muscle: 'Core', sets: 2 },
        ],
      },
      {
        name: 'Push Workout',
        emoji: '🏋️',
        subtitle: 'Chest • Shoulders • Triceps',
        exercises: [
          { name: 'Bench Press (Barbell)', muscle: 'Chest', sets: 2 },
          { name: 'Incline Bench Press (Dumbbell)', muscle: 'Chest', sets: 2 },
          { name: 'Dumbbell Fly', muscle: 'Chest', sets: 2 },
          { name: 'Overhead Press (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Lateral Raise (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Tricep Pushdown (Cable)', muscle: 'Arms', sets: 2 },
          { name: 'Skull Crusher', muscle: 'Arms', sets: 2 },
        ],
      },
      {
        name: 'Pull Workout',
        emoji: '🔙',
        subtitle: 'Back • Biceps',
        exercises: [
          { name: 'Deadlift (Barbell)', muscle: 'Back', sets: 2 },
          { name: 'Pull Up', muscle: 'Back', sets: 2 },
          { name: 'Barbell Row', muscle: 'Back', sets: 2 },
          { name: 'Seated Row (Machine)', muscle: 'Back', sets: 2 },
          { name: 'Face Pull', muscle: 'Shoulders', sets: 2 },
          { name: 'Bicep Curl (Dumbbell)', muscle: 'Arms', sets: 2 },
          { name: 'Hammer Curl', muscle: 'Arms', sets: 2 },
        ],
      },
      {
        name: 'Legs Workout',
        emoji: '🦿',
        subtitle: 'Quads • Hamstrings • Calves • Abs',
        exercises: [
          { name: 'Squat (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Romanian Deadlift (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Leg Press', muscle: 'Legs', sets: 2 },
          { name: 'Leg Curl (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Leg Extension (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Calf Raise (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Crunch', muscle: 'Core', sets: 2 },
          { name: 'Plank', muscle: 'Core', sets: 2 },
        ],
      },
    ],
  },
};