export const EXAMPLE_SPLITS_DATA = {
  'upper-lower': {
    name: 'Upper-Lower',
    description: 'Alternate between upper and lower body days',
    label: 'Upper • Lower',
    schedule: [1, 1, 0, 1, 1, 0, 1], // 2 on, 1 off cycling — Upper, Lower, Rest, Upper, Lower, Rest, Upper (Sun starts next cycle)
    workouts: [
      {
        name: 'Upper Body Workout',
        emoji: '💪',
        exercises: [
          { name: 'Flat Barbell Bench Press', muscle: 'Chest', sets: 2 },
          { name: 'Overhead Press (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Pull Up', muscle: 'Back', sets: 2 },
          { name: 'Barbell Row', muscle: 'Back', sets: 2 },
          { name: 'Lateral Raise (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Bicep Curl (Dumbbell)', muscle: 'Arms', sets: 2 },
          { name: 'Tricep Pushdown (Cable)', muscle: 'Arms', sets: 2 },
          { name: 'Face Pull', muscle: 'Shoulders', sets: 2 },
        ],
      },
      {
        name: 'Lower Body Workout',
        emoji: '🦵',
        exercises: [
          { name: 'Squat (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Deadlift (Barbell)', muscle: 'Back', sets: 2 },
          { name: 'Leg Press', muscle: 'Legs', sets: 2 },
          { name: 'Lying Hamstring Curl', muscle: 'Legs', sets: 2 },
          { name: 'Leg Extension (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Calf Raise (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Crunch', muscle: 'Core', sets: 2 },
          { name: 'Plank', muscle: 'Core', sets: 2 },
        ],
      },
    ],
  },
  'ass-aesthetics': {
    name: 'Aesthetics',
    description: 'Glute-focused lower body with upper body aesthetics — 3-day rotation',
    label: 'Glutes • Upper • Glutes & Core',
    schedule: [1, 0, 1, 0, 1, 0, 1], // Day 1, Rest, Day 2, Rest, Day 3, Rest, repeat
    workouts: [
      {
        name: 'Glutes & Legs Workout',
        emoji: '🍑',
        subtitle: 'Hip Thrusts • Squats • RDLs',
        exercises: [
          { name: 'Hip Thrust (Barbell)', muscle: 'Legs', sets: 3 },
          { name: 'Squat (Barbell)', muscle: 'Legs', sets: 3 },
          { name: 'Romanian Deadlift (Barbell)', muscle: 'Legs', sets: 3 },
          { name: 'Bulgarian Split Squat (Dumbbell)', muscle: 'Legs', sets: 2 },
          { name: 'Leg Press', muscle: 'Legs', sets: 2 },
          { name: 'Cable Kickback', muscle: 'Legs', sets: 2 },
          { name: 'Calf Raise (Machine)', muscle: 'Legs', sets: 2 },
        ],
      },
      {
        name: 'Upper Body Aesthetics Workout',
        emoji: '✨',
        subtitle: 'Shoulders • Back • Arms',
        exercises: [
          { name: 'Overhead Press (Dumbbell)', muscle: 'Shoulders', sets: 3 },
          { name: 'Lateral Raise (Dumbbell)', muscle: 'Shoulders', sets: 3 },
          { name: 'Face Pull', muscle: 'Shoulders', sets: 2 },
          { name: 'Lat Pulldown (Machine)', muscle: 'Back', sets: 3 },
          { name: 'Seated Cable Row', muscle: 'Back', sets: 2 },
          { name: 'Bicep Curl (Dumbbell)', muscle: 'Arms', sets: 2 },
          { name: 'Tricep Pushdown (Cable)', muscle: 'Arms', sets: 2 },
          { name: 'Plank', muscle: 'Core', sets: 2 },
        ],
      },
      {
        name: 'Glutes & Core Workout',
        emoji: '🔥',
        subtitle: 'Glute Isolation • Core',
        exercises: [
          { name: 'Hip Thrust (Barbell)', muscle: 'Legs', sets: 3 },
          { name: 'Glute Bridge (Barbell)', muscle: 'Legs', sets: 3 },
          { name: 'Walking Lunge (Dumbbell)', muscle: 'Legs', sets: 2 },
          { name: 'Cable Kickback', muscle: 'Legs', sets: 2 },
          { name: 'Lying Hamstring Curl', muscle: 'Legs', sets: 2 },
          { name: 'Crunch', muscle: 'Core', sets: 2 },
          { name: 'Russian Twist', muscle: 'Core', sets: 2 },
          { name: 'Plank', muscle: 'Core', sets: 2 },
        ],
      },
    ],
  },
  'ul-ppl': {
    name: 'U L P P L',
    description: 'Upper-Lower then Push-Pull-Legs — 5-day rotation',
    label: 'Upper • Lower • Push • Pull • Legs',
    schedule: [1, 1, 1, 1, 1, 0, 1], // Upper, Lower, Push, Pull, Legs, Rest, repeat
    workouts: [
      {
        name: 'Upper Body Workout',
        emoji: '💪',
        subtitle: 'Chest • Back • Shoulders • Arms',
        exercises: [
          { name: 'Flat Barbell Bench Press', muscle: 'Chest', sets: 2 },
          { name: 'Overhead Press (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Pull Up', muscle: 'Back', sets: 2 },
          { name: 'Barbell Row', muscle: 'Back', sets: 2 },
          { name: 'Lateral Raise (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Bicep Curl (Dumbbell)', muscle: 'Arms', sets: 2 },
          { name: 'Tricep Pushdown (Cable)', muscle: 'Arms', sets: 2 },
          { name: 'Face Pull', muscle: 'Shoulders', sets: 2 },
        ],
      },
      {
        name: 'Lower Body Workout',
        emoji: '🦵',
        subtitle: 'Quads • Hamstrings • Glutes • Core',
        exercises: [
          { name: 'Squat (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Deadlift (Barbell)', muscle: 'Back', sets: 2 },
          { name: 'Leg Press', muscle: 'Legs', sets: 2 },
          { name: 'Lying Hamstring Curl', muscle: 'Legs', sets: 2 },
          { name: 'Leg Extension (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Calf Raise (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Crunch', muscle: 'Core', sets: 2 },
          { name: 'Plank', muscle: 'Core', sets: 2 },
        ],
      },
      {
        name: 'Push Workout',
        emoji: '🏋️',
        subtitle: 'Chest • Shoulders • Triceps',
        exercises: [
          { name: 'Flat Barbell Bench Press', muscle: 'Chest', sets: 2 },
          { name: 'Incline Dumbbell Press', muscle: 'Chest', sets: 2 },
          { name: 'Dumbbell Fly', muscle: 'Chest', sets: 2 },
          { name: 'Overhead Press (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Lateral Raise (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Tricep Pushdown (Cable)', muscle: 'Arms', sets: 2 },
          { name: 'Skull Crushers (Ezy Bar)', muscle: 'Arms', sets: 2 },
        ],
      },
      {
        name: 'Pull Workout',
        emoji: '🔙',
        subtitle: 'Back • Biceps',
        exercises: [
          { name: 'Deadlift (Barbell)', muscle: 'Back', sets: 2 },
          { name: 'Pull Up', muscle: 'Back', sets: 2 },
          { name: 'Barbell Row', muscle: 'Back', sets: 2 },
          { name: 'Seated Cable Row', muscle: 'Back', sets: 2 },
          { name: 'Face Pull', muscle: 'Shoulders', sets: 2 },
          { name: 'Bicep Curl (Dumbbell)', muscle: 'Arms', sets: 2 },
          { name: 'Hammer Curl', muscle: 'Arms', sets: 2 },
        ],
      },
      {
        name: 'Legs Workout',
        emoji: '🦿',
        subtitle: 'Quads • Hamstrings • Calves • Abs',
        exercises: [
          { name: 'Squat (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Romanian Deadlift (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Leg Press', muscle: 'Legs', sets: 2 },
          { name: 'Lying Hamstring Curl', muscle: 'Legs', sets: 2 },
          { name: 'Leg Extension (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Calf Raise (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Crunch', muscle: 'Core', sets: 2 },
          { name: 'Plank', muscle: 'Core', sets: 2 },
        ],
      },
    ],
  },
  'push-pull-legs': {
    name: 'Push-Pull-Legs',
    description: 'Push day, pull day, legs day — 3-day rotation',
    label: 'Push • Pull • Legs',
    schedule: [1, 1, 1, 0, 1, 1, 1], // Push, Pull, Legs, Rest, repeat
    workouts: [
      {
        name: 'Push Workout',
        emoji: '🏋️',
        subtitle: 'Chest + Triceps',
        exercises: [
          { name: 'Flat Barbell Bench Press', muscle: 'Chest', sets: 2 },
          { name: 'Incline Dumbbell Press', muscle: 'Chest', sets: 2 },
          { name: 'Dumbbell Fly', muscle: 'Chest', sets: 2 },
          { name: 'Overhead Press (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Lateral Raise (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Tricep Pushdown (Cable)', muscle: 'Arms', sets: 2 },
          { name: 'Skull Crushers (Ezy Bar)', muscle: 'Arms', sets: 2 },
        ],
      },
      {
        name: 'Pull Workout',
        emoji: '🔙',
        subtitle: 'Back + Biceps',
        exercises: [
          { name: 'Deadlift (Barbell)', muscle: 'Back', sets: 2 },
          { name: 'Pull Up', muscle: 'Back', sets: 2 },
          { name: 'Barbell Row', muscle: 'Back', sets: 2 },
          { name: 'Seated Cable Row', muscle: 'Back', sets: 2 },
          { name: 'Face Pull', muscle: 'Shoulders', sets: 2 },
          { name: 'Bicep Curl (Dumbbell)', muscle: 'Arms', sets: 2 },
          { name: 'Hammer Curl', muscle: 'Arms', sets: 2 },
        ],
      },
      {
        name: 'Legs Workout',
        emoji: '🦵',
        subtitle: 'Legs + Abs',
        exercises: [
          { name: 'Squat (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Romanian Deadlift (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Leg Press', muscle: 'Legs', sets: 2 },
          { name: 'Lying Hamstring Curl', muscle: 'Legs', sets: 2 },
          { name: 'Leg Extension (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Calf Raise (Machine)', muscle: 'Legs', sets: 2 },
          { name: 'Crunch', muscle: 'Core', sets: 2 },
          { name: 'Plank', muscle: 'Core', sets: 2 },
        ],
      },
    ],
  },
  'full-body': {
    name: 'Full Body',
    description: 'Train every muscle group in one session',
    label: 'Full Body',
    schedule: [1, 0, 1, 0, 1, 0, 1], // M:FB, T:Rest, W:FB, T:Rest, F:FB, S:Rest, S:FB
    workouts: [
      {
        name: 'Full Body Workout',
        emoji: '🔥',
        subtitle: 'Chest • Back • Shoulders • Arms • Legs • Core',
        exercises: [
          { name: 'Squat (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Flat Barbell Bench Press', muscle: 'Chest', sets: 2 },
          { name: 'Barbell Row', muscle: 'Back', sets: 2 },
          { name: 'Overhead Press (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Romanian Deadlift (Barbell)', muscle: 'Legs', sets: 2 },
          { name: 'Pull Up', muscle: 'Back', sets: 2 },
          { name: 'Lateral Raise (Dumbbell)', muscle: 'Shoulders', sets: 2 },
          { name: 'Bicep Curl (Dumbbell)', muscle: 'Arms', sets: 2 },
          { name: 'Tricep Pushdown (Cable)', muscle: 'Arms', sets: 2 },
          { name: 'Plank', muscle: 'Core', sets: 2 },
        ],
      },
    ],
  },
};